AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for lambda code

Parameters:

  LambdaCodeS3Bucket:
    Type: String
    Default: lambdaCodePrjctr1


Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdaCodeS3Bucket
